# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: json.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='json.proto',
  package='hello',
  syntax='proto3',
  serialized_options=b'Z\021./hellopb;hellopb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\njson.proto\x12\x05hello\"\x9c\x01\n\x0bjsonRequest\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0f\n\x07Surname\x18\x03 \x01(\t\x12\r\n\x05\x45mail\x18\x04 \x01(\t\x12\x0e\n\x06Gender\x18\x05 \x01(\t\x12\x11\n\tIpAddress\x18\x06 \x01(\t\x12\x0f\n\x07\x43ountry\x18\x07 \x01(\t\x12\x10\n\x08Username\x18\x08 \x01(\t\x12\r\n\x05\x41gent\x18\t \x01(\t\"\x1f\n\x0cjsonResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2D\n\x0bjsonService\x12\x35\n\x08JsonFunc\x12\x12.hello.jsonRequest\x1a\x13.hello.jsonResponse\"\x00\x42\x13Z\x11./hellopb;hellopbb\x06proto3'
)




_JSONREQUEST = _descriptor.Descriptor(
  name='jsonRequest',
  full_name='hello.jsonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='hello.jsonRequest.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Name', full_name='hello.jsonRequest.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Surname', full_name='hello.jsonRequest.Surname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Email', full_name='hello.jsonRequest.Email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Gender', full_name='hello.jsonRequest.Gender', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='IpAddress', full_name='hello.jsonRequest.IpAddress', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Country', full_name='hello.jsonRequest.Country', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Username', full_name='hello.jsonRequest.Username', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Agent', full_name='hello.jsonRequest.Agent', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=178,
)


_JSONRESPONSE = _descriptor.Descriptor(
  name='jsonResponse',
  full_name='hello.jsonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='hello.jsonResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=211,
)

DESCRIPTOR.message_types_by_name['jsonRequest'] = _JSONREQUEST
DESCRIPTOR.message_types_by_name['jsonResponse'] = _JSONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

jsonRequest = _reflection.GeneratedProtocolMessageType('jsonRequest', (_message.Message,), {
  'DESCRIPTOR' : _JSONREQUEST,
  '__module__' : 'json_pb2'
  # @@protoc_insertion_point(class_scope:hello.jsonRequest)
  })
_sym_db.RegisterMessage(jsonRequest)

jsonResponse = _reflection.GeneratedProtocolMessageType('jsonResponse', (_message.Message,), {
  'DESCRIPTOR' : _JSONRESPONSE,
  '__module__' : 'json_pb2'
  # @@protoc_insertion_point(class_scope:hello.jsonResponse)
  })
_sym_db.RegisterMessage(jsonResponse)


DESCRIPTOR._options = None

_JSONSERVICE = _descriptor.ServiceDescriptor(
  name='jsonService',
  full_name='hello.jsonService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=213,
  serialized_end=281,
  methods=[
  _descriptor.MethodDescriptor(
    name='JsonFunc',
    full_name='hello.jsonService.JsonFunc',
    index=0,
    containing_service=None,
    input_type=_JSONREQUEST,
    output_type=_JSONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_JSONSERVICE)

DESCRIPTOR.services_by_name['jsonService'] = _JSONSERVICE

# @@protoc_insertion_point(module_scope)
