// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: json.proto

package hellopb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type JsonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Surname   string `protobuf:"bytes,3,opt,name=Surname,json=surname,proto3" json:"Surname,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Gender    string `protobuf:"bytes,5,opt,name=Gender,json=gender,proto3" json:"Gender,omitempty"`
	IpAddress string `protobuf:"bytes,6,opt,name=IpAddress,json=ipAddress,proto3" json:"IpAddress,omitempty"`
	Country   string `protobuf:"bytes,7,opt,name=Country,json=country,proto3" json:"Country,omitempty"`
	Username  string `protobuf:"bytes,8,opt,name=Username,json=username,proto3" json:"Username,omitempty"`
	Agent     string `protobuf:"bytes,9,opt,name=Agent,json=agent,proto3" json:"Agent,omitempty"`
}

func (x *JsonRequest) Reset() {
	*x = JsonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_json_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonRequest) ProtoMessage() {}

func (x *JsonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_json_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonRequest.ProtoReflect.Descriptor instead.
func (*JsonRequest) Descriptor() ([]byte, []int) {
	return file_json_proto_rawDescGZIP(), []int{0}
}

func (x *JsonRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *JsonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JsonRequest) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *JsonRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *JsonRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *JsonRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *JsonRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *JsonRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *JsonRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type JsonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *JsonResponse) Reset() {
	*x = JsonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_json_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonResponse) ProtoMessage() {}

func (x *JsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_json_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonResponse.ProtoReflect.Descriptor instead.
func (*JsonResponse) Descriptor() ([]byte, []int) {
	return file_json_proto_rawDescGZIP(), []int{1}
}

func (x *JsonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_json_proto protoreflect.FileDescriptor

var file_json_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6a, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x22, 0xe3, 0x01, 0x0a, 0x0b, 0x6a, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x49, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x0c, 0x6a, 0x73, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0x44, 0x0a, 0x0b, 0x6a, 0x73, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x4a, 0x73, 0x6f, 0x6e, 0x46, 0x75, 0x6e, 0x63, 0x12, 0x12,
	0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x70, 0x62, 0x3b, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_json_proto_rawDescOnce sync.Once
	file_json_proto_rawDescData = file_json_proto_rawDesc
)

func file_json_proto_rawDescGZIP() []byte {
	file_json_proto_rawDescOnce.Do(func() {
		file_json_proto_rawDescData = protoimpl.X.CompressGZIP(file_json_proto_rawDescData)
	})
	return file_json_proto_rawDescData
}

var file_json_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_json_proto_goTypes = []interface{}{
	(*JsonRequest)(nil),  // 0: hello.jsonRequest
	(*JsonResponse)(nil), // 1: hello.jsonResponse
}
var file_json_proto_depIdxs = []int32{
	0, // 0: hello.jsonService.JsonFunc:input_type -> hello.jsonRequest
	1, // 1: hello.jsonService.JsonFunc:output_type -> hello.jsonResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_json_proto_init() }
func file_json_proto_init() {
	if File_json_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_json_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_json_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_json_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_json_proto_goTypes,
		DependencyIndexes: file_json_proto_depIdxs,
		MessageInfos:      file_json_proto_msgTypes,
	}.Build()
	File_json_proto = out.File
	file_json_proto_rawDesc = nil
	file_json_proto_goTypes = nil
	file_json_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// JsonServiceClient is the client API for JsonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JsonServiceClient interface {
	JsonFunc(ctx context.Context, in *JsonRequest, opts ...grpc.CallOption) (*JsonResponse, error)
}

type jsonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJsonServiceClient(cc grpc.ClientConnInterface) JsonServiceClient {
	return &jsonServiceClient{cc}
}

func (c *jsonServiceClient) JsonFunc(ctx context.Context, in *JsonRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, "/hello.jsonService/JsonFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JsonServiceServer is the server API for JsonService service.
type JsonServiceServer interface {
	JsonFunc(context.Context, *JsonRequest) (*JsonResponse, error)
}

// UnimplementedJsonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJsonServiceServer struct {
}

func (*UnimplementedJsonServiceServer) JsonFunc(context.Context, *JsonRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JsonFunc not implemented")
}

func RegisterJsonServiceServer(s *grpc.Server, srv JsonServiceServer) {
	s.RegisterService(&_JsonService_serviceDesc, srv)
}

func _JsonService_JsonFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonServiceServer).JsonFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.jsonService/JsonFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonServiceServer).JsonFunc(ctx, req.(*JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JsonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.jsonService",
	HandlerType: (*JsonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JsonFunc",
			Handler:    _JsonService_JsonFunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "json.proto",
}
